# Generated by Django 3.0.3 on 2021-05-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_appointments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='First_Name',
            new_name='First_name',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='Last_Name',
            new_name='Last_name',
        ),
    ]
