# Generated by Django 3.0.3 on 2021-05-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20210512_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
