# Generated by Django 3.0.3 on 2021-05-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_auto_20210512_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('speciality', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('hospital_name', models.CharField(max_length=20)),
            ],
        ),
    ]
