# Generated by Django 3.0.3 on 2021-05-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_doctorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientid', models.PositiveIntegerField(null=True)),
                ('patientName', models.CharField(max_length=20)),
                ('patientPhone', models.CharField(max_length=20)),
                ('appointmentDate', models.CharField(max_length=20)),
                ('doctorName', models.CharField(max_length=20)),
                ('symptom', models.CharField(max_length=40)),
                ('medicine', models.CharField(max_length=50)),
                ('doctorFee', models.PositiveIntegerField()),
                ('medicineFee', models.PositiveIntegerField()),
                ('otherCharges', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
            ],
        ),
    ]
