# Generated by Django 3.0.3 on 2021-05-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='doctor_username',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='appointments',
            name='patient_username',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='doctor_username',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
